# å¯é€‰ï¼Œå°†æ˜¾ç¤ºåœ¨ GitHub å­˜å‚¨åº“çš„â€œæ“ä½œâ€é€‰é¡¹å¡ä¸­çš„å·¥ä½œæµåç§°
name: Release CI

# æŒ‡å®šæ­¤å·¥ä½œæµçš„è§¦å‘å™¨
on:
  push:
    # åŒ¹é…ç‰¹å®šæ ‡ç­¾ (refs/tags)
    tags:
      - 'v*' # æ¨é€äº‹ä»¶åŒ¹é… v*, ä¾‹å¦‚ v1.0ï¼Œv20.15.10 ç­‰æ¥è§¦å‘å·¥ä½œæµ

# éœ€è¦è¿è¡Œçš„ä½œä¸šç»„åˆ
jobs:
  # ä»»åŠ¡ï¼šåˆ›å»º release ç‰ˆæœ¬
  create-release:
    runs-on: ubuntu-latest
    outputs:
      RELEASE_UPLOAD_ID: ${{ steps.create_release.outputs.id }}

    steps:
      - uses: actions/checkout@v2
      # æŸ¥è¯¢ç‰ˆæœ¬å·ï¼ˆtagï¼‰
      - name: Query version number
        id: get_version
        shell: bash
        run: |
          echo "using version tag ${GITHUB_REF:10}"
          echo ::set-output name=version::"${GITHUB_REF:10}"

      # æ ¹æ®æŸ¥è¯¢åˆ°çš„ç‰ˆæœ¬å·åˆ›å»º release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: '${{ steps.get_version.outputs.VERSION }}'
          release_name: 'Simple Todo List ${{ steps.get_version.outputs.VERSION }}'
          body: 'ğŸ¥³See the assets to download this version and install.'
  
  # ç¼–è¯‘ Tauri
  build-tauri:
    needs: create-release
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2

      # å®‰è£… Node.js
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      # å®‰è£… pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.3
        with:
          version: latest
          run_install: true
 
      
      # å®‰è£… Rust
      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      # ä½¿ç”¨ Rust ç¼“å­˜ï¼ŒåŠ å¿«å®‰è£…é€Ÿåº¦
      - uses: Swatinem/rust-cache@v1

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf


      # å®‰è£…ä¾èµ–æ‰§è¡Œæ„å»ºï¼Œä»¥åŠæ¨é€ github release
      - name: Build app 
        run: pnpm tauri build
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: 'SimpleTodoList${{ steps.get_version.outputs.VERSION }}'
          #  ${{ needs.create-release.outputs.RELEASE_UPLOAD_ID }}
          #  releaseName: 'Simple Todo List ${{ steps.get_version.outputs.VERSION }}'
